server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: employeeservice
          uri: lb://employeeservice #load balanced uri
          predicates:
            - Path=/api/v1/employees/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10 #Trong 1s nap 10 token
                redis-rate-limiter.burstCapacity: 20 #Toi da trong bucket co 20 token(trong 1s goi tren 20 request se khong duoc)
                redis-rate-limiter.requestedTokens: 1 #1 request se can 1 token
            - KeyAuthFilter
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true